export const GET_GUIDES = "GET_GUIDES";
export const GET_HOTELS = "GET_HOTELS";
export const SEARCH_HOTELS = "GET_HOTELS";
export const SET_LOADING = "SET_LOADING";
export const GUIDES_ERROR = "GUIDES_ERROR";
export const HOTELS_ERROR = "HOTELS_ERROR";
export const GET_CURRENT_LOCATION = "GET_CURRENT_LOCATION";
export const GET_INPUT = "GET_INPUT";
export const TOGGLE_SEARCH_RESULT = "TOGGLE_SEARCH_RESULT";
export const GET_ADDRESS_PREDICTIONS = "GET_ADDRESS_PREDICTIONS";
export const TRANSPORT_ERROR = "TRANSPORT_ERROR";

